[package]
name = "cotsh"
version = "0.1.0"
edition = "2024"

[dependencies]
crossterm.workspace = true
colored.workspace = true
once_cell.workspace = true
regex.workspace = true
getset.workspace = true