[workspace]
members = ["shell"]


[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3


[workspace.dependencies]
crossterm = "0.29.0"
colored = "3.0.0"
once_cell = "1.21.3"
regex = "1.11.1"
getset = "0.1.6"
tabled = "0.20.0"
chrono = "0.4.41"
humantime = "2.2.0"
figlet-rs = "0.1.5"