#!/bin/zsh

# Path to your Rust project

PROJECT_PATH=~/Documents/rust_shell/Cargo.toml

# Check the first argument
# shellcheck disable=SC1046
if [[ "$1" == "-dev" ]]; then
  echo "Running in DEBUG mode..."
  cargo run --manifest-path $PROJECT_PATH -- --debug
elif [[ "$1" == "release" ]]; then
  echo "Running in RELEASE mode..."
  cargo run --release --manifest-path $PROJECT_PATH -- --release
elif [[ "$1" == "-test" ]]; then
  echo "Running in test mode..."
  cargo test --manifest-path $PROJECT_PATH
else
  echo "Running in NORMAL mode..."
  cargo run --manifest-path $PROJECT_PATH
fi